build_task: pipelines/gradle/tasks/gradle-assemble.yml # don't change
deploy_dev_task: pipelines/cf/tasks/blue-green-deploy.yml # don't change

# set this to '<first_initial><lastname>-eureka' ex: sgreenberg-eureka
app_name: eureka-server
jar_name: relka-eurekaserver

# https url of your eureka app github fork.  ex: https://github.com/spgreenberg/eureka-server.git
github_app_repo_uri: https://github.com/dawg2k3/eureka-server.git
github_app_repo_branch: master # don't change

# https url of your training-pipelines-initial fork.  ex: https://github.com/spgreenberg/training-pipelines-initial.git
github_pipelines_repo_uri: https://github.com/dawg2k3/training-pipelines-initial.git
github_pipelines_repo_branch: master # don't change

version_bucket: rscale-training-bucket # don't change
version_bucket_region_name: us-west-2 # don't change

# set to '<first_initial><lastname>-eureka-version'.  ex: sgreenberg-eureka-version
version_key: relka-eurekaserver-version
initial_version: 0.0.1

# set to '<first_initial><lastname>-eureka-(.*).jar'.  ex: sgreenberg-eureka-(.*).jar
artifact_regexp: relka-eurekaserver-(.*).jar
artifact_bucket: rscale-training-bucket # don't change
artifact_bucket_region_name: us-west-2 # don't change

# set to cf api endpoint
cf_dev_api: https://api.run.pivotal.io
# set to your org
cf_dev_organization: rscale-training-2
# set to your space
cf_dev_space: rameshwar.elka@cgi.com
# set to 'eureka-<first_initial><lastname>'. ex: eureka-sgreenberg
cf_dev_hostname: eurekaserver-relka
# set to the apps domain for your CF
cf_dev_domain: cfapps.io
# set to the dev manifest path in your eureka app repository. ex: dev-manifest.yml
cf_dev_manifest: dev-manifest.yml
